# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  configuration: vizro-core/mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
    # TODO: Once build process is out of beta for RTD, aim to implement custom build using hatch, removing requirement.txt
    # See: https://docs.readthedocs.io/en/latest/build-customization.html#override-the-build-process
    # See: https://github.com/readthedocs/readthedocs.org/issues/10706
    - requirements: vizro-core/docs/requirements.txt
