name: Check versions and build-publish

on:
    push:
      branches: [main]
    pull_request:
      branches:
        - "main"

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install --upgrade hatch

    - name: Check which package needs to be released
      run: |
        packages=("vizro" "vizro-ai" "foo")

        for string in "${packages[@]}"; do
            cd vizro-core
            version=$(hatch version)
            cd ..
            python tools/github_actions_release.py $string $version
        done

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1