name: Check versions and build-publish

on:
    push:
      branches: [main]
    pull_request:
      branches:
        - "main"

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install --upgrade hatch

    - name: Check which 📦 needs to be released
      run: |
        packages=("vizro" "vizro-core")

        for string in "${packages[@]}"; do
            if [[ "$string" == "vizro" ]]; then
                cd vizro-core
            else
                cd $string
            fi
            version=$(hatch version)
            cd ..
            python tools/github_actions_release.py $string $version
        done


    - name: Set outputs
      id: version_check
      run: |
        echo "new_release=${{ env.NEW_RELEASE }}" >> $GITHUB_OUTPUT
        echo "package_name=${{ env.PACKAGE_NAME }}" >> $GITHUB_OUTPUT
        echo "package_version=${{ env.PACKAGE_VERSION }}" >> $GITHUB_OUTPUT
    outputs:
      new_release: ${{ steps.version_check.outputs.new_release }}
      package_name: ${{ steps.version_check.outputs.package_name }}
      package_version: ${{ steps.version_check.outputs.package_version }}
    # - name: Create GitHub Release
    #   uses: softprops/action-gh-release@v1

    # - name: Publish distribution 📦 to PyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     packages-dir: vizro-core/dist
    #     password: abc1234