name: Check versions and build-publish

on:
    push:
      branches: [main]
    pull_request:
      branches:
        - "main"

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Check which package needs to be released
      run: |
        packages=("vizro" "vizro-ai" "foo")

        for string in "${packages[@]}"; do
            cd vizro-core
            version=$(hatch version)
            cd ..
            echo "Checking package $string for version $version"
            # You can add your actions or commands here for each string
            python tools/github_actions_release.py $string $version
        done